-- Table: invoice_lines
-- Description: Stores lines for AP invoices.

CREATE TABLE invoice_lines (
    invoice_line_id  NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id       NUMBER NOT NULL,
    line_number      NUMBER NOT NULL,
    line_amount      NUMBER NOT NULL,
    description      VARCHAR2(240),
    po_line_id       NUMBER,
    creation_date    DATE DEFAULT SYSDATE NOT NULL,
    created_by       NUMBER NOT NULL,
    last_update_date DATE DEFAULT SYSDATE NOT NULL,
    last_updated_by  NUMBER NOT NULL,
    CONSTRAINT fk_il_invoice_id FOREIGN KEY (invoice_id) REFERENCES invoices(invoice_id),
    CONSTRAINT fk_il_po_line_id FOREIGN KEY (po_line_id) REFERENCES purchase_order_lines(po_line_id)
);

COMMENT ON TABLE invoice_lines IS 'Stores lines for AP invoices.';
COMMENT ON COLUMN invoice_lines.invoice_line_id IS 'Unique identifier for the invoice line.';
COMMENT ON COLUMN invoice_lines.invoice_id IS 'Foreign key referencing the invoice header.';
COMMENT ON COLUMN invoice_lines.line_number IS 'Line number within the invoice.';
COMMENT ON COLUMN invoice_lines.line_amount IS 'Amount for this line.';
COMMENT ON COLUMN invoice_lines.po_line_id IS 'Reference to the purchase order line matched to this invoice line.';
