-- Table: invoices
-- Description: Stores headers for AP invoices.

CREATE TABLE invoices (
    invoice_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_num      VARCHAR2(50) NOT NULL,
    supplier_id      NUMBER NOT NULL,
    invoice_date     DATE NOT NULL,
    invoice_amount   NUMBER NOT NULL,
    invoice_currency VARCHAR2(3) DEFAULT 'USD',
    status           VARCHAR2(25) DEFAULT 'NEVER APPROVED' CHECK (status IN ('NEVER APPROVED', 'APPROVED', 'CANCELLED', 'PAID')),
    source           VARCHAR2(80),
    creation_date    DATE DEFAULT SYSDATE NOT NULL,
    created_by       NUMBER NOT NULL,
    last_update_date DATE DEFAULT SYSDATE NOT NULL,
    last_updated_by  NUMBER NOT NULL,
    CONSTRAINT fk_inv_supplier_id FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id)
);

COMMENT ON TABLE invoices IS 'Stores headers for AP invoices.';
COMMENT ON COLUMN invoices.invoice_id IS 'Unique identifier for the invoice header.';
COMMENT ON COLUMN invoices.invoice_num IS 'Invoice number provided by the supplier.';
COMMENT ON COLUMN invoices.supplier_id IS 'Foreign key referencing the supplier.';
COMMENT ON COLUMN invoices.invoice_date IS 'Date of the invoice.';
COMMENT ON COLUMN invoices.invoice_amount IS 'Total amount of the invoice.';
COMMENT ON COLUMN invoices.status IS 'Status of the invoice (NEVER APPROVED, APPROVED, CANCELLED, PAID).';
