-- Table: payments
-- Description: Stores details of payments made to suppliers.

CREATE TABLE payments (
    payment_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id       NUMBER NOT NULL,
    payment_date     DATE DEFAULT SYSDATE NOT NULL,
    payment_amount   NUMBER NOT NULL,
    payment_method   VARCHAR2(30) CHECK (payment_method IN ('CHECK', 'EFT', 'WIRE', 'CREDIT_CARD')),
    check_number     VARCHAR2(30),
    creation_date    DATE DEFAULT SYSDATE NOT NULL,
    created_by       NUMBER NOT NULL,
    last_update_date DATE DEFAULT SYSDATE NOT NULL,
    last_updated_by  NUMBER NOT NULL,
    CONSTRAINT fk_pay_invoice_id FOREIGN KEY (invoice_id) REFERENCES invoices(invoice_id)
);

COMMENT ON TABLE payments IS 'Stores details of payments made to suppliers.';
COMMENT ON COLUMN payments.payment_id IS 'Unique identifier for the payment.';
COMMENT ON COLUMN payments.invoice_id IS 'Foreign key referencing the invoice being paid.';
COMMENT ON COLUMN payments.payment_date IS 'Date the payment was made.';
COMMENT ON COLUMN payments.payment_amount IS 'Amount paid.';
COMMENT ON COLUMN payments.payment_method IS 'Method of payment (CHECK, EFT, WIRE, CREDIT_CARD).';
