-- Table: purchase_order_lines
-- Description: Stores lines for purchase orders.

CREATE TABLE purchase_order_lines (
    po_line_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_header_id          NUMBER NOT NULL,
    line_num              NUMBER NOT NULL,
    item_description      VARCHAR2(240) NOT NULL,
    unit_meas_lookup_code VARCHAR2(25) NOT NULL,
    unit_price            NUMBER NOT NULL,
    quantity              NUMBER NOT NULL,
    requisition_line_id   NUMBER,
    creation_date         DATE DEFAULT SYSDATE NOT NULL,
    created_by            NUMBER NOT NULL,
    last_update_date      DATE DEFAULT SYSDATE NOT NULL,
    last_updated_by       NUMBER NOT NULL,
    CONSTRAINT fk_pol_header_id FOREIGN KEY (po_header_id) REFERENCES purchase_orders(po_header_id),
    CONSTRAINT fk_pol_req_line_id FOREIGN KEY (requisition_line_id) REFERENCES purchase_requisition_lines(requisition_line_id)
);

COMMENT ON TABLE purchase_order_lines IS 'Stores lines for purchase orders.';
COMMENT ON COLUMN purchase_order_lines.po_line_id IS 'Unique identifier for the PO line.';
COMMENT ON COLUMN purchase_order_lines.po_header_id IS 'Foreign key referencing the PO header.';
COMMENT ON COLUMN purchase_order_lines.line_num IS 'Line number within the PO.';
COMMENT ON COLUMN purchase_order_lines.item_description IS 'Description of the item.';
COMMENT ON COLUMN purchase_order_lines.unit_price IS 'Unit price of the item.';
COMMENT ON COLUMN purchase_order_lines.quantity IS 'Quantity ordered.';
COMMENT ON COLUMN purchase_order_lines.requisition_line_id IS 'Reference to the originating requisition line.';
