-- Table: purchase_orders
-- Description: Stores headers for purchase orders.

CREATE TABLE purchase_orders (
    po_header_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    segment1         VARCHAR2(20) NOT NULL UNIQUE, -- PO Number
    supplier_id      NUMBER NOT NULL,
    supplier_site_id NUMBER NOT NULL,
    buyer_id         NUMBER NOT NULL,
    description      VARCHAR2(240),
    status           VARCHAR2(25) DEFAULT 'INCOMPLETE' CHECK (status IN ('INCOMPLETE', 'PENDING', 'APPROVED', 'REJECTED', 'CLOSED')),
    creation_date    DATE DEFAULT SYSDATE NOT NULL,
    created_by       NUMBER NOT NULL,
    last_update_date DATE DEFAULT SYSDATE NOT NULL,
    last_updated_by  NUMBER NOT NULL,
    CONSTRAINT fk_po_supplier_id FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id),
    CONSTRAINT fk_po_site_id FOREIGN KEY (supplier_site_id) REFERENCES supplier_sites(site_id)
);

COMMENT ON TABLE purchase_orders IS 'Stores headers for purchase orders.';
COMMENT ON COLUMN purchase_orders.po_header_id IS 'Unique identifier for the PO header.';
COMMENT ON COLUMN purchase_orders.segment1 IS 'Purchase Order number.';
COMMENT ON COLUMN purchase_orders.supplier_id IS 'Foreign key referencing the supplier.';
COMMENT ON COLUMN purchase_orders.supplier_site_id IS 'Foreign key referencing the supplier site.';
COMMENT ON COLUMN purchase_orders.buyer_id IS 'Employee ID of the buyer.';
COMMENT ON COLUMN purchase_orders.status IS 'Status of the PO (INCOMPLETE, PENDING, APPROVED, REJECTED, CLOSED).';
