-- Table: purchase_requisition_lines
-- Description: Stores lines for purchase requisitions.

CREATE TABLE purchase_requisition_lines (
    requisition_line_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requisition_header_id NUMBER NOT NULL,
    line_number           NUMBER NOT NULL,
    item_description      VARCHAR2(240) NOT NULL,
    unit_meas_lookup_code VARCHAR2(25) NOT NULL,
    unit_price            NUMBER NOT NULL,
    quantity              NUMBER NOT NULL,
    need_by_date          DATE,
    creation_date         DATE DEFAULT SYSDATE NOT NULL,
    created_by            NUMBER NOT NULL,
    last_update_date      DATE DEFAULT SYSDATE NOT NULL,
    last_updated_by       NUMBER NOT NULL,
    CONSTRAINT fk_prl_header_id FOREIGN KEY (requisition_header_id) REFERENCES purchase_requisitions(requisition_header_id)
);

COMMENT ON TABLE purchase_requisition_lines IS 'Stores lines for purchase requisitions.';
COMMENT ON COLUMN purchase_requisition_lines.requisition_line_id IS 'Unique identifier for the requisition line.';
COMMENT ON COLUMN purchase_requisition_lines.requisition_header_id IS 'Foreign key referencing the requisition header.';
COMMENT ON COLUMN purchase_requisition_lines.line_number IS 'Line number within the requisition.';
COMMENT ON COLUMN purchase_requisition_lines.item_description IS 'Description of the item being requested.';
COMMENT ON COLUMN purchase_requisition_lines.unit_price IS 'Unit price of the item.';
COMMENT ON COLUMN purchase_requisition_lines.quantity IS 'Quantity requested.';
