-- Table: purchase_requisitions
-- Description: Stores headers for purchase requisitions.

CREATE TABLE purchase_requisitions (
    requisition_header_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requisition_number    VARCHAR2(30) NOT NULL UNIQUE,
    preparer_id           NUMBER NOT NULL,
    description           VARCHAR2(240),
    status                VARCHAR2(25) DEFAULT 'INCOMPLETE' CHECK (status IN ('INCOMPLETE', 'PENDING', 'APPROVED', 'REJECTED')),
    creation_date         DATE DEFAULT SYSDATE NOT NULL,
    created_by            NUMBER NOT NULL,
    last_update_date      DATE DEFAULT SYSDATE NOT NULL,
    last_updated_by       NUMBER NOT NULL
);

COMMENT ON TABLE purchase_requisitions IS 'Stores headers for purchase requisitions.';
COMMENT ON COLUMN purchase_requisitions.requisition_header_id IS 'Unique identifier for the requisition header.';
COMMENT ON COLUMN purchase_requisitions.requisition_number IS 'Unique requisition number.';
COMMENT ON COLUMN purchase_requisitions.preparer_id IS 'Employee ID of the person who prepared the requisition.';
COMMENT ON COLUMN purchase_requisitions.status IS 'Status of the requisition (INCOMPLETE, PENDING, APPROVED, REJECTED).';
