-- Table: receiving_lines
-- Description: Stores lines for goods receipts.

CREATE TABLE receiving_lines (
    shipment_line_id   NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_header_id NUMBER NOT NULL,
    po_line_id         NUMBER NOT NULL,
    quantity_received  NUMBER NOT NULL,
    uom_code           VARCHAR2(25) NOT NULL,
    creation_date      DATE DEFAULT SYSDATE NOT NULL,
    created_by         NUMBER NOT NULL,
    last_update_date   DATE DEFAULT SYSDATE NOT NULL,
    last_updated_by    NUMBER NOT NULL,
    CONSTRAINT fk_rl_header_id FOREIGN KEY (shipment_header_id) REFERENCES receiving_headers(shipment_header_id),
    CONSTRAINT fk_rl_po_line_id FOREIGN KEY (po_line_id) REFERENCES purchase_order_lines(po_line_id)
);

COMMENT ON TABLE receiving_lines IS 'Stores lines for goods receipts.';
COMMENT ON COLUMN receiving_lines.shipment_line_id IS 'Unique identifier for the receipt line.';
COMMENT ON COLUMN receiving_lines.shipment_header_id IS 'Foreign key referencing the receipt header.';
COMMENT ON COLUMN receiving_lines.po_line_id IS 'Foreign key referencing the purchase order line.';
COMMENT ON COLUMN receiving_lines.quantity_received IS 'Quantity of goods received.';
COMMENT ON COLUMN receiving_lines.uom_code IS 'Unit of measure code.';
