-- Table: receiving_headers
-- Description: Stores headers for goods receipts.

CREATE TABLE receiving_headers (
    shipment_header_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    receipt_num        VARCHAR2(30) NOT NULL UNIQUE,
    supplier_id        NUMBER NOT NULL,
    receipt_date       DATE DEFAULT SYSDATE NOT NULL,
    received_by        NUMBER NOT NULL,
    creation_date      DATE DEFAULT SYSDATE NOT NULL,
    created_by         NUMBER NOT NULL,
    last_update_date   DATE DEFAULT SYSDATE NOT NULL,
    last_updated_by    NUMBER NOT NULL,
    CONSTRAINT fk_rh_supplier_id FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id)
);

COMMENT ON TABLE receiving_headers IS 'Stores headers for goods receipts.';
COMMENT ON COLUMN receiving_headers.shipment_header_id IS 'Unique identifier for the receipt header.';
COMMENT ON COLUMN receiving_headers.receipt_num IS 'Unique receipt number.';
COMMENT ON COLUMN receiving_headers.supplier_id IS 'Foreign key referencing the supplier.';
COMMENT ON COLUMN receiving_headers.receipt_date IS 'Date the goods were received.';
