-- Table: supplier_sites
-- Description: Stores address and site information for suppliers.

CREATE TABLE supplier_sites (
    site_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id      NUMBER NOT NULL,
    site_name        VARCHAR2(15) NOT NULL,
    address_line1    VARCHAR2(240),
    address_line2    VARCHAR2(240),
    city             VARCHAR2(60),
    state            VARCHAR2(150),
    zip_code         VARCHAR2(20),
    country          VARCHAR2(60),
    phone_number     VARCHAR2(30),
    email_address    VARCHAR2(2000),
    creation_date    DATE DEFAULT SYSDATE NOT NULL,
    created_by       NUMBER NOT NULL,
    last_update_date DATE DEFAULT SYSDATE NOT NULL,
    last_updated_by  NUMBER NOT NULL,
    CONSTRAINT fk_ss_supplier_id FOREIGN KEY (supplier_id) REFERENCES suppliers(supplier_id)
);

COMMENT ON TABLE supplier_sites IS 'Stores address and site information for suppliers.';
COMMENT ON COLUMN supplier_sites.site_id IS 'Unique identifier for the supplier site.';
COMMENT ON COLUMN supplier_sites.supplier_id IS 'Foreign key referencing the supplier.';
COMMENT ON COLUMN supplier_sites.site_name IS 'Name of the site (e.g., OFFICE, WAREHOUSE).';
