-- Table: suppliers
-- Description: Stores master data for suppliers.

CREATE TABLE suppliers (
    supplier_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_name    VARCHAR2(240) NOT NULL,
    supplier_number  VARCHAR2(30) NOT NULL UNIQUE,
    tax_payer_id     VARCHAR2(30),
    supplier_status  VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (supplier_status IN ('ACTIVE', 'INACTIVE', 'ON_HOLD')),
    creation_date    DATE DEFAULT SYSDATE NOT NULL,
    created_by       NUMBER NOT NULL,
    last_update_date DATE DEFAULT SYSDATE NOT NULL,
    last_updated_by  NUMBER NOT NULL
);

COMMENT ON TABLE suppliers IS 'Stores master data for suppliers.';
COMMENT ON COLUMN suppliers.supplier_id IS 'Unique identifier for the supplier.';
COMMENT ON COLUMN suppliers.supplier_name IS 'Name of the supplier.';
COMMENT ON COLUMN suppliers.supplier_number IS 'Unique supplier number assigned by the system.';
COMMENT ON COLUMN suppliers.tax_payer_id IS 'Tax payer identification number.';
COMMENT ON COLUMN suppliers.supplier_status IS 'Status of the supplier (ACTIVE, INACTIVE, ON_HOLD).';
